server:
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
# 接口文档
knife4j:
  enable: true
  openapi:
    title: 开发文档
    description: "项目文档"
    concat: Dyz
    version: v1.0
    group:
      test1:
        group-name: group
        api-rule: package
        api-rule-resources:
          - com.dyzhome.controller